#!/bin/sh

weather() {
    cat ~/.weather_report.txt
}

network() {
    if grep -q "UP" ~/.network_status.txt
    then
        echo "| "
    else
        echo "| "
    fi
}

battery_capacity() {
    cat "/sys/class/power_supply/BAT0/capacity"
}

battery_percentage() {
    echo "|  $(battery_capacity)"%" |"
}

status_bar() {
    echo "$(weather) $(network) $(battery_percentage) $(date)"
}

while true; do
    xsetroot -name " $(status_bar) "
    sleep 1
done

